name: Issue processing
on:
  issues:
    types:
      - labeled
jobs:
  process-grpc-issue:
    if: github.event.label.name == 'grpc/subsvc'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            await github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["gRPC"]
            })

  process-signalr-issue:
    if: github.event.label.name == 'aspnetcore-signalr/subsvc'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            await github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["SignalR"]
            })

  process-blazorhybrid-issue:
    if: github.event.label.name == 'blazor-hybrid/subsvc'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            await github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["Blazor Hybrid"]
            })
            await github.rest.issues.addAssignees({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              assignees: ["guardrex", "BethMassi"]
            })
            await github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: [":watch: Not Triaged"]
            })

  process-blazor-issue:
    if: github.event.label.name == 'blazor/subsvc'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `### ğŸ˜ğŸ–ï¸ğŸŒ´ &mdash; **ğŸ¦– is OOF until July 1** &mdash; ğŸğŸ„â€â™€ï¸ğŸ¦© 

            Hello! The green dinosaur guy ğŸ¦– (guardrex) is OOF from 6/24 to 6/28 and will return on July 1. Critical bug reports will be addressed during this period, but please standby for the ğŸ¦– to return on July 1 for all other non-critical issues.`
            })
            await github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["Blazor"]
            })
            await github.rest.issues.addAssignees({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              assignees: ["guardrex"]
            })
            await github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: [":watch: Not Triaged"]
            })
