name: Issue processing
on:
  issues:
    types:
      - labeled
jobs:
  process-grpc-issue:
    if: github.event.label.name == 'aspnetcore-grpc/tech'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            await github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["gRPC"]
            })

  process-signalr-issue:
    if: github.event.label.name == 'aspnetcore-signalr/tech'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            await github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["SignalR"]
            })

  process-blazorhybrid-issue:
    if: github.event.label.name == 'aspnetcore-blazorhybrid/tech'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            await github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["Blazor Hybrid"]
            })
            await github.rest.issues.addAssignees({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              assignees: ["guardrex", "BethMassi"]
            })
            await github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: [":watch: Not Triaged"]
            })

  process-blazor-issue:
    if: github.event.label.name == 'aspnetcore-blazor/tech'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `### ðŸŽ‰ðŸ¥³ ***Happy New Year!*** ðŸ’ƒðŸ•º

            A green dinosaur ðŸ¦– will be along shortly to assist. *Stand-by ........*`
            })
            await github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["Blazor"]
            })
            await github.rest.issues.addAssignees({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              assignees: ["guardrex"]
            })
            await github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: [":watch: Not Triaged"]
            })
